CREATE TABLESPACE EMPRESADG08 DATAFILE 'D:\oracle\EMPRESADG08' SIZE
100M AUTOEXTEND OFF;

CREATE USER DG08 IDENTIFIED BY DG08PWD DEFAULT TABLESPACE EMPRESADG08
TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON EMPRESADG08;

GRANT CREATE SESSION, CREATE TABLE, DELETE ANY TABLE, SELECT ANY
DICTIONARY, CREATE ANY SEQUENCE TO DG08;